apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-app
  template:
    metadata:
      labels:
        app: jenkins-app
    spec:
      containers:
        - name: jenkins-app
          image: 838342381657.dkr.ecr.ap-south-1.amazonaws.com/deploy-kube
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-app-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32124
