apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-prod
  template:
    metadata:
      labels:
        app: jenkins-prod
    spec:
      containers:
        - name: jenkins-prod
          image: 838342381657.dkr.ecr.ap-south-1.amazonaws.com/deploy-kube
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-svc
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32121
